//
//  HomeInteractor.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func showGreeting(request: Home.ShowGreeting.Request)
}

protocol HomeDataStore
{
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Show greeting
  
  func showGreeting(request: Home.ShowGreeting.Request)
  {
    let userID = AuthenticationWorker().getUserID()
    let response = Home.ShowGreeting.Response(userID: userID)
    presenter?.presentShowGreeting(response: response)
  }
}
