//
//  HomePresenter.swift
//  Simple
//
//  Created by Raymond Law on 6/25/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentShowGreeting(response: Home.ShowGreeting.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Show greeting
  
  func presentShowGreeting(response: Home.ShowGreeting.Response)
  {
    let viewModel = Home.ShowGreeting.ViewModel(userID: response.userID)
    viewController?.displayShowGreeting(viewModel: viewModel)
  }
}
